using System;
using CustomPlayerEffects;
using Exiled.API.Enums;
using Exiled.API.Features;
using Footprinting;
using InventorySystem.Items;
using InventorySystem.Items.Firearms.Modules;
using InventorySystem.Items.Firearms.ShotEvents;
using PlayerStatsSystem;

namespace RGM.Modes;

/// <summary>
/// Applies Particle Disruptor damage while preserving normal cancellation and
/// attacker attribution. DamageReduction and BodyshotReduction are pre-compensated.
/// </summary>
public static class ApplyFixedDamage
{
    private static int _activeApplications;

    /// <summary>
    /// Gets whether the current synchronous Hurting event was generated by this helper.
    /// </summary>
    public static bool IsApplying => _activeApplications > 0;

    public static bool Apply(Player attacker, Player target, float damage) =>
        Apply(attacker, target, damage, DeathTranslations.Unknown);

    public static bool Apply(
        Player attacker,
        Player target,
        float damage,
        DeathTranslation deathReason)
    {
        // Kept for source compatibility. Fixed damage now uses the native
        // Particle Disruptor handler, whose death reason is not configurable.
        _ = deathReason;

        if (attacker == null)
            throw new ArgumentNullException(nameof(attacker));

        if (target == null)
            throw new ArgumentNullException(nameof(target));

        if (float.IsNaN(damage) || float.IsInfinity(damage) || damage <= 0f || !target.IsAlive)
            return false;

        var handler = new DisruptorDamageHandler(
            new DisruptorShotEvent(
                ItemIdentifier.None,
                new Footprint(attacker.ReferenceHub),
                DisruptorActionModule.FiringState.FiringRapid),
            target.Position,
            damage);

        CompensateDamageModifier(target, handler, EffectType.DamageReduction);
        CompensateDamageModifier(target, handler, EffectType.BodyshotReduction);

        _activeApplications++;
        try
        {
            return target.ReferenceHub.playerStats.DealDamage(handler);
        }
        finally
        {
            _activeApplications--;
        }
    }

    private static void CompensateDamageModifier(
        Player target,
        StandardDamageHandler handler,
        EffectType effectType)
    {
        if (!target.TryGetEffect(effectType, out StatusEffectBase effect) ||
            effect is not IDamageModifierEffect { DamageModifierActive: true } modifier)
        {
            return;
        }

        float damageModifier = modifier.GetDamageModifier(
            handler.Damage,
            handler,
            handler.Hitbox);

        if (damageModifier is > 0f and < 1f)
            handler.Damage /= damageModifier;
    }
}
